stages:
  get_data:
    cmd: python3 src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - smsspamcollection
  preprocess:
    cmd: python3 src/text_preprocessing.py
    deps:
    - src/text_preprocessing.py
    outs:
    - output/preprocessor.joblib
